version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_DB_USER}
      APP_USER_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata

  transaction-service:
    build: .
    container_name: transaction-service
    restart: always
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER: oracle.jdbc.OracleDriver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  oracle_data:
