server:
  port: 8080

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
    username: appuser
    password: apppass
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

      # ðŸ”¥ CRITICAL FIX
      initialization-fail-timeout: -1
      connection-test-query: SELECT 1 FROM DUAL

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
